version: '2'
services:
  web:
    build: .
    container_name: web
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
