# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04049eed19cb4ce91edb4a6cf5ec2f4ca11681ef555dbc757bec7de1ea29d107f24947bee17bb93ae0215a06c178a42ff484530b0f215fc3678248b71f7fa9bb

test:
  secret_key_base: 31a73313ca0a32dab2f225f1512e1265a66309f583dea1c0a1240cb70a03a1fbd9391c1251b09c85bc05e68a6355764fc0735ffeecfae819e281bd5d0f5c32c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
